build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
   version: 3.11
   install:
      - requirements: docs/requirements.txt
   setup_py_install: true
